### ISSUE TITLE
callofliberty

### ISSUE THREAD

**Issue by pokemaster974** [Sphinxroot/Streaming-Site#1]
Sorry for creating this issue, but I hope you can help me about this.

With the help you give my on [iptv repo](https://github.com/iptv-org/iptv/issues/13224#issuecomment-1596318818) I success to modify my script to record the TV (it's for recording the journal tv).
The part of my AutoHotKey script is :
`RunWait, %ComSpec% /c ffmpeg.exe -headers "Referer: http://www.callofliberty.fr/tv/1-TF1/1-TF1.php" -i "http://www.callofliberty.fr/stream/TF1/manifest.m3u8" -c copy -t 00:50:00 "%NomFichierTF1Backup2%", %A_WorkingDir%, Hide,`

I thought I was able to doing it for France 2 with this part of code :
`RunWait, %ComSpec% /c ffmpeg.exe -headers "Referer: http://www.callofliberty.fr/tv/2-france.2/2-france.2.php" -i "http://www.callofliberty.fr/stream/france.2/master.m3u8" -c copy -t 00:50:00 "%NomFichierFrance2%", %A_WorkingDir%, Hide,`

But I obtain an error :

> D:\youtube-dl\ffmpeg\bin>ffmpeg.exe -headers "Referer: http://www.callofliberty.fr/tv/2-france.2/2-france.2.php" -i "http://www.callofliberty.fr/stream/france.2/master.m3u8" -c copy -t 00:01:00 "test.ts"
> ffmpeg version 2023-05-15-git-2953ebe7b6-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
>   built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
>   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
>   libavutil      58.  7.100 / 58.  7.100
>   libavcodec     60. 12.100 / 60. 12.100
>   libavformat    60.  5.100 / 60.  5.100
>   libavdevice    60.  2.100 / 60.  2.100
>   libavfilter     9.  8.100 /  9.  8.100
>   libswscale      7.  2.100 /  7.  2.100
>   libswresample   4. 11.100 /  4. 11.100
>   libpostproc    57.  2.100 / 57.  2.100
> [http @ 00000297de34fe00] No trailing CRLF found in HTTP header. Adding it.
> [hls @ 00000297de34f440] Skip ('#EXT-X-VERSION:5')
> [hls @ 00000297de34f440] Opening 'https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_118000=10005.m3u8' for reading
> [https @ 00000297de35cd80] HTTP error 403 Forbidden
> [hls @ 00000297de34f440] parse_playlist error Server returned 403 Forbidden (access denied) [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_118000=10005.m3u8]
> [hls @ 00000297de34f440] Opening 'https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_400000=10004.m3u8' for reading
> [https @ 00000297de412c80] HTTP error 403 Forbidden
> [hls @ 00000297de34f440] parse_playlist error Server returned 403 Forbidden (access denied) [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_400000=10004.m3u8]
> [hls @ 00000297de34f440] Opening 'https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_950000=10003.m3u8' for reading
> [https @ 00000297de35ccc0] HTTP error 403 Forbidden
> [hls @ 00000297de34f440] parse_playlist error Server returned 403 Forbidden (access denied) [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_950000=10003.m3u8]
> [hls @ 00000297de34f440] Opening 'https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_1400000=10002.m3u8' for reading
> [https @ 00000297de372bc0] HTTP error 403 Forbidden
> [hls @ 00000297de34f440] parse_playlist error Server returned 403 Forbidden (access denied) [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_1400000=10002.m3u8]
> [hls @ 00000297de34f440] Opening 'https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_2500000=10001.m3u8' for reading
> [https @ 00000297de8f6bc0] HTTP error 403 Forbidden
> [hls @ 00000297de34f440] parse_playlist error Server returned 403 Forbidden (access denied) [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_2500000=10001.m3u8]
> [hls @ 00000297de34f440] Opening 'https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_5000000=10000.m3u8' for reading
> [https @ 00000297de832cc0] HTTP error 403 Forbidden
> [hls @ 00000297de34f440] parse_playlist error Server returned 403 Forbidden (access denied) [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_5000000=10000.m3u8]
> [hls @ 00000297de34f440] Empty segment [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_118000=10005.m3u8]
> [hls @ 00000297de34f440] Empty segment [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_400000=10004.m3u8]
> [hls @ 00000297de34f440] Empty segment [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_950000=10003.m3u8]
> [hls @ 00000297de34f440] Empty segment [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_1400000=10002.m3u8]
> [hls @ 00000297de34f440] Empty segment [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_2500000=10001.m3u8]
> [hls @ 00000297de34f440] Empty segment [https://simulcast-p.ftven.fr/ZXhwPTE2ODczNTk1Njd+YWNsPSUyZip+aG1hYz1kNDNmOGEyODRiMDlhYWVlZmNkNDA3ZWYxYjkwMWU4Y2YwODJmYmQwM2QxMGM0OGQ3MzMyY2Y1Mzc4Y2ZmMjk0/simulcast/France_2/hls_fr2/France_2-mp4a_96000_fra=20000-avc1_5000000=10000.m3u8]
> Input #0, hls, from 'http://www.callofliberty.fr/stream/france.2/master.m3u8':
>   Duration: N/A, bitrate: N/A
>   Program 0
>     Metadata:
>       variant_bitrate : 255244
>   Program 1
>     Metadata:
>       variant_bitrate : 584055
>   Program 2 
>     Metadata:
>       variant_bitrate : 1225356
>   Program 3
>     Metadata:
>       variant_bitrate : 1750055
>   Program 4
>     Metadata:
>       variant_bitrate : 3032655
>   Program 5
>     Metadata:
>       variant_bitrate : 5947655
> Output #0, mpegts, to 'test.ts':
> [out#0/mpegts @ 00000297de419440] Output file does not contain any stream

Do you know if there is a solution for recording France2 with ffmpeg (normally I use captvty but it's not CLI-compatible so automation is not possible) ?

Regards.

**Comment by Sphinxroot** [comment]
#EXTINF:0,4. France 2
http://livetv.ktv.zone/4/play.m3u8
#EXTINF:0,5. France 3
http://livetv.ktv.zone/5/play.m3u8
#EXTINF:0,16. France 4
http://livetv.ktv.zone/16/play.m3u8
#EXTINF:0,7. France 5
http://livetv.ktv.zone/7/play.m3u8
unstable  sadly  

and tnt site dont offer them anymore
 original  legal  link  are now tokenezied  and login + vpn required   but can be piped upon streamlink advanced scripting

**Comment by pokemaster974** [comment]
Thanks for your reply, I tried it with `ffmpeg.exe -i "http://livetv.ktv.zone/4/play.m3u8" -c copy -t 00:00:50 "test.ts"`

but got an error :
```
ffmpeg version 2023-05-15-git-2953ebe7b6-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  7.100 / 58.  7.100
  libavcodec     60. 12.100 / 60. 12.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.100 /  9.  8.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[hls @ 0000019fc318f180] Skip ('#EXT-X-VERSION:3')
[hls @ 0000019fc318f180] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0000019fc318f180] Skip ('#EXT-X-DISCONTINUITY')
    Last message repeated 4 times
[hls @ 0000019fc318f180] Opening 'http://files.k-net.fr/ktv-misc/no_source.ts?channel=4' for reading
[http @ 0000019fc319ea00] HTTP error 502 Bad Gateway
[hls @ 0000019fc318f180] Failed to open segment 168747322 of playlist 0
[hls @ 0000019fc318f180] Segment 168747322 of playlist 0 failed too many times, skipping
[hls @ 0000019fc318f180] Opening 'http://files.k-net.fr/ktv-misc/no_source.ts?channel=4' for reading
[http @ 0000019fc319ea00] HTTP error 502 Bad Gateway
[hls @ 0000019fc318f180] Failed to open segment 168747323 of playlist 0
[hls @ 0000019fc318f180] Segment 168747323 of playlist 0 failed too many times, skipping
[hls @ 0000019fc318f180] Opening 'http://files.k-net.fr/ktv-misc/no_source.ts?channel=4' for reading
[http @ 0000019fc319ea00] HTTP error 502 Bad Gateway
[hls @ 0000019fc318f180] Failed to open segment 168747324 of playlist 0
[hls @ 0000019fc318f180] Segment 168747324 of playlist 0 failed too many times, skipping
[hls @ 0000019fc318f180] Skip ('#EXT-X-VERSION:3')
[hls @ 0000019fc318f180] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0000019fc318f180] Skip ('#EXT-X-DISCONTINUITY')
    Last message repeated 4 times
[hls @ 0000019fc318f180] Opening 'http://files.k-net.fr/ktv-misc/no_source.ts?channel=4' for reading
[http @ 0000019fc31b7e80] HTTP error 502 Bad Gateway
[hls @ 0000019fc318f180] Failed to open segment 168747325 of playlist 0
[hls @ 0000019fc318f180] Segment 168747325 of playlist 0 failed too many times, skipping
[http @ 0000019fc319ea80] Opening 'http://livetv.ktv.zone/4/play.m3u8' for reading
[hls @ 0000019fc318f180] Skip ('#EXT-X-VERSION:3')     
[hls @ 0000019fc318f180] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0000019fc318f180] Skip ('#EXT-X-DISCONTINUITY') 
    Last message repeated 4 times
[http @ 0000019fc319ea80] Opening 'http://livetv.ktv.zone/4/play.m3u8' for reading
[hls @ 0000019fc318f180] Skip ('#EXT-X-VERSION:3')
[hls @ 0000019fc318f180] Skip ('#EXT-X-ALLOW-CACHE:NO')
[hls @ 0000019fc318f180] Skip ('#EXT-X-DISCONTINUITY')
    Last message repeated 4 times
```

I don't know if my cmd line is bad or just that I can't do this.
Regards.

**Comment by pokemaster974** [comment]
If there is no more solution, you can close the issue if you want.
Regards.

**Comment by pokemaster974** [comment]
Hi, is http://www.callofliberty.fr down ?
